#!/bin/bash

if (($# == 2));
then
    path_to_file="/etc/nginx/sites-available/"$1".conf"
    path_to_enable="/etc/nginx/sites-enabled/"$1".conf"
    path_to_folder=$2
    
    mkdir -p $path_to_folder
    
    eval certbot certonly -d $1
    echo 'server {
        listen 80;
        server_name '$1';
        return 301 https://$server_name$request_uri;
        }
    server {

        server_name '$1';
        listen 443 ssl http2;

        root '$path_to_folder';

        # SSL Configuration - Replace the example <domain> with your domain
        ssl_certificate /etc/letsencrypt/live/'$1'/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/'$1'/privkey.pem;
        ssl_session_cache shared:SSL:10m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
        ssl_prefer_server_ciphers on;


        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header Referrer-Policy "strict-origin-when-cross-origin";

        index index.html index.htm index.php;

        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ \.php$ {
            fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }' > $path_to_file
    ln -s $path_to_file $path_to_enable
    nginx -s reload
    echo "Complete !"
else
    echo "please enter nginx-config <domain> <path_to_root>"
fi
